theme: jekyll-theme-cayman
title: CMMID project repository
github:
  is_project_page: false

exclude: ["README.md", "_shinyapp/template.md"]

collections:
  shinyapp:
    output: true

defaults:
  -
    scope:
      path: ""
      type: shinyapp
    values:
      layout: shinyapp
